config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :news do
    match '/scrape', to: 'news#scrape', via: :post, on: :collection
    match '/search', to: 'news#search', via: :get, on: :collection
  end
  root to: 'news#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
# frozen_string_literal: true

class News < ApplicationRecord
  scope :filter_by_title, ->(title) { where title: title }
  scope :filter_by_origin, ->(origin) { where origin: origin }
  scope :filter_by_tags, ->(tags) { where('tags like ?', "%#{tags}%") }
end

app/models/news_crawler.rb
# frozen_string_literal: true

class NewsCrawler
  # Secretaria da Cultura
  def self.parse_url_cultura(url)
    unparsed_page = HTTParty.get(url)
    parsed_page = Nokogiri::HTML(unparsed_page)

    posts_container = parsed_page.css('ul#posts-list li.post')

    posts_container.each do |post|
      item = {}

      item[:title] = post.css('h2 a').text
      item[:subtitle] = post.css('p').text
      item[:url] = post.css('h2 a').map { |link| link['href'] }[0]
      item[:publishing_date] = parse_date(post.css('.details').text)
      item[:crawl_date] = Time.now
      item[:news_body] = parse_child_page(item[:url])
      item[:origin] = 'Cultura'

      new_piece = News.where(item).first_or_create
      puts new_piece
    end
  end

  # Secretaria do Desenvolvimento Social
  def self.parse_url_desenvolvimento(url)
    unparsed_page = HTTParty.get(url)
    parsed_page = Nokogiri::HTML(unparsed_page)

    posts_container = parsed_page.css('#content-core article')

    posts_container.each do |post|
      item = {}

      item[:title] = post.css('h2.tileHeadline a').text
      item[:subtitle] = post.css('p.tileBody .description').text
      item[:url] = post.css('h2.tileHeadline a').map { |link| link['href'] }[0]
      item[:publishing_date] = parse_date(post.css('.documentByLine .summary-view-icon').text)
      item[:crawl_date] = Time.now
      item[:news_body] = parse_child_page(item[:url])
      item[:origin] = 'Desenvolvimento'

      new_piece = News.where(item).first_or_create
      puts new_piece
    end
  end

  def self.parse_child_page(child_page)
    puts "parsing: #{child_page}"
    text_body = ''
    unparsed_page = HTTParty.get(child_page)
    parsed_page = Nokogiri::HTML(unparsed_page)

    paragraphs = parsed_page.css('p')

    paragraphs.each do |paragraph|
      text_body += paragraph.text
      text_body += "\n"
    end

    text_body
  end

  def self.parse_date(str)
    str.match(%r{\d{2}/\d{2}/\d{4}.\d{2}h\d{2}}).to_s.to_datetime
  end

  def self.parse_website(url)
    unparsed_url = HTTParty.get(url)
    parsed_url = Nokogiri::HTML(unparsed_url)

    if url.match(/cultura/)
      last_page = parsed_url.css('.last a').map { |link| link['href'] }[0].match(/\d+/).to_s.to_i
      (1..1).each do |i|
        parse_url_cultura("#{url}/page/#{i}")
      end
    else
      last_page = parsed_url.css('a.pagina').text.to_i
      (0..1).each do |i|
        parse_url_desenvolvimento("#{url}?b_start:int=#{i * 30}")
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/news_controller.rb
# frozen_string_literal: true

class NewsController < ApplicationController
  before_action :set_news, only: %i[show edit update destroy]

  # GET /news
  # GET /news.json
  def index
    @pagy, @news = pagy(News.all)
  end

  def search
    @pagy, @news = pagy(News.where("concat_ws(' ' , title, origin, tags) LIKE ?", "%#{params[:q]}%"))
  end

  # GET /news/1
  # GET /news/1.json
  def show; end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit; end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  def scrape
    # websites = {}

    # websites[:cultura] = 'http://cultura.gov.br/categoria/noticias/'
    # websites[:desenvolvimento] = 'https://www.gov.br/cidadania/pt-br/noticias-e-conteudos/desenvolvimento-social/noticias-desenvolvimento-social'

    t1 = Thread.new {
      NewsCrawler.parse_website('http://cultura.gov.br/categoria/noticias/')
    }

    t2 = Thread.new {
      NewsCrawler.parse_website('https://www.gov.br/cidadania/pt-br/noticias-e-conteudos/desenvolvimento-social/noticias-desenvolvimento-social')
    }

    flash[:notice] = "The crawler is being executed. Please go back to see the crawled data."
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_news
    @news = News.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def news_params
    params.require(:news).permit(:url, :title, :subtitle, :publishing_date, :crawl_date, :news_body, :tags)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend

  def pagy_get_params(params)
    params.except(:anything, :not, :useful).merge!(something: 'more useful')
  end
end

app/helpers/news_helper.rb
# frozen_string_literal: true

module NewsHelper
  def news_author(author); end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Crawler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <script>
    // Sucess message when the scraper finishes
    const scrapeButton = document.querySelector('.scrape-button');
    scrapeButton.addEventListener('click', function(e) {
      this.setAttribute('value', '');
      this.className = "spinner-border text-primary mb-5 mt-5";
    });

  </script>
</html>

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :publishing_date %>
    <%= form.datetime_select :publishing_date %>
  </div>

  <div class="field">
    <%= form.label :crawl_date %>
    <%= form.datetime_select :crawl_date %>
  </div>

  <div class="field">
    <%= form.label :news_body %>
    <%= form.text_area :news_body %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<div class="text-center">
<%= button_to 'Scrape new posts', scrape_news_index_path, {class: 'btn btn-primary mb-5 mt-5 scrape-button'} %>
<p id="notice"><%= notice %></p>

<h1 class="title mb-4">Scraped posts</h1>
</div>

<%= form_tag(search_news_index_path, method: :get) do %>
  <input name="q" type="text" placeholder="Search for title, tag or origin of post">
  <%= submit_tag ("Search") %>
<% end %>

<div class="container-fluid">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Subtitle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.subtitle %></td>
        <td role="button"><%= link_to 'Show', news, { class: 'btn btn-info '} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
<br>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/scrape.html.erb
<p class="alert alert-primary" role="alert">
  <%= notice %>
</p>
<div class="alert alert-primary" role="alert">
  <%= alert %>
</div>

<%= link_to 'Go Back', root_path %>

app/views/news/search.html.erb
<div class="text-center">
<%= button_to 'Scrape new posts', scrape_news_index_path, {class: 'btn btn-primary mb-5 mt-5'} %>
<p id="notice"><%= notice %></p>

<h1 class="title mb-4">Scraped posts</h1>
</div>

<%= form_tag(search_news_index_path, method: :get) do %>
  <input name="q" type="text" placeholder="Search title, tag or origin of post">
  <%= submit_tag ("Search") %>
<% end %>

<div class="container-fluid">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Subtitle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.subtitle %></td>
        <td role="button"><%= link_to 'Show', news, { class: 'btn btn-info '} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
<br>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @news.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @news.subtitle %>
</p>

<p>
  <strong>Publishing date:</strong>
  <%= @news.publishing_date %>
</p>

<p>
  <strong>Crawl date:</strong>
  <%= @news.crawl_date %>
</p>

<p>
  <strong>News body:</strong>
  <%= @news.news_body %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @news.tags %>
</p>

<%= link_to 'Edit', edit_news_path(@news), {class: 'btn btn-secondary'} %> |
<%= link_to 'Back', news_index_path, {class: 'btn btn-primary'} %>